[project]
name = "src"
version = "0.0.1"
authors = [{name = "sandeep", email = "ss.suthar.004@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}